name: Flutter Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [android, ios, web]
        include:
          - os: android
            build_command: flutter build apk --split-per-abi
            artifact_name: app-android
            artifact_pattern: build/app/outputs/flutter-apk/app-*.apk
          - os: ios
            build_command: flutter build ios --no-codesign
            artifact_name: app-ios
            artifact_pattern: build/ios/iphoneos/*.ipa
          - os: web
            build_command: flutter build web
            artifact_name: web
            artifact_pattern: build/web/**

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x' # Or specify your desired Flutter version

      - name: Get dependencies
        run: flutter pub get

      - name: Build ${{ matrix.os }}
        run: |
          echo "Building for ${{ matrix.os }}"
          ${{ matrix.build_command }}

      - name: Upload ${{ matrix.artifact_name }} Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_pattern }}

  desktop:
    needs: build
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        include:
          - os: macos-latest
            build_command: flutter build macos
            artifact_name: app-macos
            artifact_pattern: build/macos/Build/Products/Release/*.app.zip
          - os: windows-latest
            build_command: flutter build windows
            artifact_name: app-windows
            artifact_pattern: build/windows/runner/Release/*.zip
          - os: ubuntu-latest
            build_command: flutter build linux
            artifact_name: app-linux
            artifact_pattern: build/linux/x64/release/*.tar.gz

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x' # Or specify your desired Flutter version

      - name: Get dependencies
        run: flutter pub get

      - name: Build ${{ matrix.os }}
        run: |
          echo "Building for ${{ matrix.os }}"
          ${{ matrix.build_command }}

      - name: Upload ${{ matrix.artifact_name }} Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_pattern }}