name: Flutter CI Build

# Controls when the workflow will run
on:
  push:
    branches: [ main ] # Or your default branch
  pull_request:
    branches: [ main ] # Or your default branch
  workflow_dispatch: # Allows manual triggering

jobs:
  #----------------------------------------------------
  # Build Android (APK and AppBundle)
  #----------------------------------------------------
  build_android:
    name: Build Flutter (Android)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          # cache: true

      # Use 'pub upgrade' instead of 'pub get' to fetch latest plugin versions
      # This is needed to resolve v1/v2 Android embedding issues (e.g., path_provider_android)
      - name: Upgrade Flutter dependencies
        run: flutter pub upgrade # Changed from 'flutter pub get'

      # NOTE: Analyze and test steps removed.

      - name: Build Flutter APK (Release)
        run: flutter build apk --release

      - name: Build Flutter AppBundle (Release)
        run: flutter build appbundle --release

      - name: Upload Android APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload Android AppBundle Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-appbundle
          path: build/app/outputs/bundle/release/app-release.aab

  #----------------------------------------------------
  # Build iOS (Requires macOS runner)
  #----------------------------------------------------
  build_ios:
    name: Build Flutter (iOS)
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          # cache: true

      - name: Get Flutter dependencies
        run: flutter pub get # Keep 'get' here as iOS build was working

      # NOTE: Analyze and test steps removed.

      - name: Build Flutter iOS (Release - No Code Signing)
        run: flutter build ios --release --no-codesign

      - name: Upload iOS App Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-ios-app # Contains the .app bundle
          path: build/ios/iphoneos/Runner.app # Upload the .app directory

  #----------------------------------------------------
  # Build Web
  #----------------------------------------------------
  build_web:
    name: Build Flutter (Web)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          # cache: true

      - name: Enable Flutter Web
        run: flutter config --enable-web

      - name: Get Flutter dependencies
        run: flutter pub get # Keep 'get' here as Web build was working

      # NOTE: Analyze and test steps removed.

      - name: Build Flutter Web (Release)
        run: flutter build web --release

      - name: Upload Web Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-web
          path: build/web

  #----------------------------------------------------
  # Build Linux
  #----------------------------------------------------
  build_linux:
    name: Build Flutter (Linux)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Linux dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          # cache: true

      - name: Enable Flutter Linux Desktop
        run: flutter config --enable-linux-desktop

      - name: Get Flutter dependencies
        run: flutter pub get # Keep 'get' here as Linux build was working

      # NOTE: Analyze and test steps removed.

      - name: Build Flutter Linux (Release)
        run: flutter build linux --release

      - name: Upload Linux Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-linux
          path: build/linux/x64/release/bundle

  #----------------------------------------------------
  # Build macOS (Requires macOS runner)
  #----------------------------------------------------
  build_macos:
    name: Build Flutter (macOS)
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          # cache: true

      - name: Enable Flutter macOS Desktop
        run: flutter config --enable-macos-desktop

      - name: Get Flutter dependencies
        run: flutter pub get # Keep 'get' here as macOS build was working

      # NOTE: Analyze and test steps removed.

      - name: Build Flutter macOS (Release)
        run: flutter build macos --release

      - name: Upload macOS App Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-macos-app # Contains the .app bundle
          path: build/macos/Build/Products/Release/*.app

  #----------------------------------------------------
  # Build Windows (Requires Windows runner)
  #----------------------------------------------------
  build_windows:
    name: Build Flutter (Windows)
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          # cache: true

      - name: Enable Flutter Windows Desktop
        run: flutter config --enable-windows-desktop

      - name: Get Flutter dependencies
        run: flutter pub get # Keep 'get' here as Windows build was working

      # NOTE: Analyze and test steps removed.

      - name: Build Flutter Windows (Release)
        run: flutter build windows --release

      - name: Upload Windows Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-windows
          path: build/windows/x64/runner/Release/